config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'

  get 'password_reset/edit'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  get 'signup' => 'users#new'
  patch 'delete' => 'users#destroy'

  resources :static_pages

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_reset,      only: [:new, :create, :edit, :update]

end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  before_action :get_user, only: [:edit, :udpate]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only:[:edit, :update]

  def new
  end

  def edit
  end

  def create
    	user = User.find_by email: params[:password_reset][:email].downcase
  		if user
        user.create_reset_digest
  			user.send_password_reset_email
  			flash[:info] = "Emails sent with password reset instructions"
  			redirect_to root_url
  		else
  			flash[:danger] = "Email address not found"
  			render 'new'	
  		end
  end

  def update
    if params[:user][:password].empty?
      flash.now[:danger] ="Password can't be blank"
      render 'edit'
    elsif @user.update_attributes!(user_params)
      sign_in @user
      flash.now[:info] = "Password has been reset"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  #C10: get user for password reset
  def get_user
    @user = User.find_by(email: params[:email])
  end
  #C10: Confirm valid User
  def valid_user
    get_user
    unless @user && @user.activated? && @user.authenticate?(:reset, params[:id])
      redirect_to root_url
    end
  end
  def check_expiration
    if @user.password_reset_expired?
      flash[:error] = "Password reset has expirated"
      redirect_to new_password_reser_url
    end
  end

end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_reset/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>
<% flash.each do|key,value| %>
<div class= "alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id]), method: :patch) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_reset/new.html.erb
<% provide(:title, "Forgot password") %>
<h1>Forgot password</h1>

<% flash.each do|key,value| %>
<div class= "alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_reset_index_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>