config/routes.rb
Rails.application.routes.draw do
  get 'password_reset/new'

  get 'password_reset/edit'

  resources :users

  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'

  get 'signup' => 'users#new'
  patch 'delete' => 'users#destroy'

  resources :static_pages

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :password_reset,      only: [:new, :create, :edit, :update]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="#">Rails Tutorials</a> by Liu Huang Zhu
	</small>
	<nav>
		<ul>
			<li><%= link_to "About",  about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://facebook.com">Facebook</a>
			</li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "sample app", home_path, id: "logo" %>
			<nav>
				<ul class="nav navbar-nav pull-right">
					<li><%= link_to "Home", home_path %></li>
					<li><%= link_to "About",about_path %></li>
					<% if signed_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", @current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign out", signout_path, method: :delete %>
								</li>
							</ul>
						</li>
						<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title yield(:title) %></title>
	<%= stylesheet_link_tag "application", media: "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
	 <%= render 'layouts/header' %>
		
	</header>
			<div class="container">
			<%= yield %>
			<%= render 'layouts/footer' %>
			</div>
</body>
</html>